{"name": "test_update_exercise", "status": "broken", "statusDetails": {"message": "TypeError: object Response can't be used in 'await' expression", "trace": "self = <test_async_exercises.TestExercises object at 0x10a7fe810>\nfunction_exercise = ExerciseFixture(request=CreateExerciseRequestSchema(title='Probably social hope national each.', course_id='556d16bc-e...ld light similar situation look head. Record similar growth security buy report who fast.', estimated_time='3 weeks')))\nexercises_client = <clients.exercises.exercises_client.ExercisesClient object at 0x10ac2bda0>\n\n    async def test_update_exercise(self,\n                                 function_exercise: ExerciseFixture,\n                                 exercises_client: ExercisesClient):\n        request_data = UpdateExerciseRequestSchema()\n        uuid = function_exercise.response.exercise.id\n    \n>       response = await exercises_client.update_exercise_api(uuid, request_data)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       TypeError: object Response can't be used in 'await' expression\n\ntest_async_exercises.py:69: TypeError"}, "start": 1751656521388, "stop": 1751656521393, "uuid": "c3828e99-b150-47b9-91d4-d979f1dccc47", "historyId": "63fde9b13887e33114af9143a2dc69a0", "testCaseId": "63fde9b13887e33114af9143a2dc69a0", "fullName": "tests.exprcises.test_async_exercises.TestExercises#test_update_exercise", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.exprcises"}, {"name": "suite", "value": "test_async_exercises"}, {"name": "subSuite", "value": "TestExercises"}, {"name": "host", "value": "VIS-SSQ05N"}, {"name": "thread", "value": "77794-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.exprcises.test_async_exercises"}]}